### ISSUE TITLE
s3_sync_meta issue

### ISSUE THREAD

**Issue by dbinetti** [etianen/django-s3-storage#24]
when trying to sync the meta data after switching from `django-storages-redux` i get:

```
django-admin s3_sync_meta django.core.files.storage.default_storage
Syncing meta for django.core.files.storage.default_storage
Traceback (most recent call last):
  File "/app/.heroku/python/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django_s3_storage/management/commands/s3_sync_meta.py", line 22, in handle
    for path in storage.sync_meta_iter():
  File "/app/.heroku/python/lib/python2.7/site-packages/django_s3_storage/storage.py", line 368, in sync_meta_iter
    for path in sync_meta_impl(""):
  File "/app/.heroku/python/lib/python2.7/site-packages/django_s3_storage/storage.py", line 354, in sync_meta_impl
    metadata = key.metadata.copy()
AttributeError: 'NoneType' object has no attribute 'metadata'
```

However, I suspect this is user error; specifically, I'm not sure what is meant by `path.to.your.storage` in the documentation.  I'm trying to run this on my heroku instance, and I'm not at all clear what the 'path' is in this context...

Thanks.

**Comment by etianen** [comment]
Ah, I think you're using django-s3-storage 0.9.9, and have just been hit by an unintended consequence of the fix for #18.

Try the master branch. I've just pushed up what is almost certainly a fix for your problem.

**Comment by dbinetti** [comment]
yep, fixed.

**Comment by etianen** [comment]
Cool, I'll get a new release out later today.

**Comment by etianen** [comment]
0.9.10 is out

**Comment by dbinetti** [comment]
Might be a regression here.  On 0.11.0

```
~ $ django-admin s3_sync_meta django.core.files.storage.default_storage
Syncing meta for django.core.files.storage.default_storage
Traceback (most recent call last):
  File "/app/.heroku/python/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django_s3_storage/management/commands/s3_sync_meta.py", line 30, in handle
    for path in storage.sync_meta_iter():
  File "/app/.heroku/python/lib/python2.7/site-packages/django_s3_storage/storage.py", line 333, in sync_meta_iter
    obj = self.meta(name)
  File "/app/.heroku/python/lib/python2.7/site-packages/django_s3_storage/storage.py", line 32, in _do_wrap_errors
    raise IOError("S3Storage error at {!r}: {}".format(name, force_text(ex)))
IOError: S3Storage error at '.': An error occurred (404) when calling the HeadObject operation: Not Found
~ $ 
```

**Comment by etianen** [comment]
There will hopefully be a fix for this in master.

I think that you have a key called "." in your bucket, which is causing the key name normalization to break. I've made django-s3-storage stop exploding when it encounters this, but you should probably get rid of it.

**Comment by dbinetti** [comment]
Fixed on `master`. That said, I checked and do not have a key `.` in the
bucket, so something else might be doing that....

**Comment by etianen** [comment]
The error you posted specifically mentioned a key "." in its stack trace.
Are you absolutely certain it's not there? It's possible that the tools
you're using to list the bucket can't show it either, as it's an invalid
file name on Unix and windows.

**Comment by dbinetti** [comment]
i don't dispute that it's weird, but I can say that I can not see any
object referred to by a `.` key through either the AWS web or cli
interface.  so this might be an undocumented thing for AWS, or it might be
a hint to what's happening, or it might be I simply can't see whats there.

**Comment by etianen** [comment]
Any chance you could give me temporary access to the bucket so I can investigate? I'd imagine the answer is almost certainly not!

Otherwise, I can have a go at writing a script to try and find the problematic key.

**Comment by dbinetti** [comment]
key word is...almost....  :-)

yeah, if you promise not to screw anything up I can give you access.
 what's the easiest way?  some ad-hoc IAM permissions I presume?

**Comment by etianen** [comment]
Yes, I think an ad-hoc IAM role would do. If you're feeling paranoid, I can take a PGP email to dave@etianen.com with the details (or a non-PGP email, if you're not feeling paranoid).

My intention is to write a read-only script to iterate over all the keys in the bucket, which will hopefully catch the offending key.
