### ISSUE TITLE
sorl-thumbnail is incompitable with django-s3-storage

### ISSUE THREAD

**Issue by Flimm** [etianen/django-s3-storage#60]
I am trying to run this command, which is part of [sorl-thumbnail](https://github.com/jazzband/sorl-thumbnail):

```
$ python manage.py thumbnail clear_delete_all
Clear the Key Value Store ... [Done]
Starting new HTTPS connection (1): s3-eu-west-1.amazonaws.com
Delete all thumbnail files in THUMBNAIL_PREFIX ... Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "python/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "python/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "python/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "python/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "python/lib/python3.6/site-packages/sorl/thumbnail/management/commands/thumbnail.py", line 74, in handle
    delete_all_thumbnails()
  File "python/lib/python3.6/site-packages/sorl/thumbnail/images.py", line 222, in delete_all_thumbnails
    path = os.path.join(storage.location, settings.THUMBNAIL_PREFIX)
  File "python/lib/python3.6/site-packages/django/utils/functional.py", line 239, in inner
    return func(self._wrapped, *args)
AttributeError: 'S3Storage' object has no attribute 'location'
```

It seems that `sorl-thumbnail` expects there to be a `location` attribute on `S3Storage`.

**Comment by etianen** [comment]
It looks like sort-thumbnail is assuming that the file is stored on the
hard drive. This is clearly not the case when the file is stored in S3!

**Comment by Flimm** [comment]
It works with `django-storages`. I think `location` is simply the S3 prefix that may be used in that case.

**Comment by etianen** [comment]
Hmm, in which case they're not using the django file storage API correctly.
The location field is not a part of the django file storage API.

https://docs.djangoproject.com/en/1.11/ref/files/storage/#the-storage-class

If the library relies on internal implementation details of storage
classes, it's gonna blow up.
