### ISSUE TITLE
Access Denied when calling the PutObject operation

### ISSUE THREAD

**Issue by edgarroman** [etianen/django-s3-storage#96]
So found this out when setting up a Django static files site.  
When creating the bucket, if you select 'Block all public access' then when you run:
`python manage.py collectstatic`

You will get an error of 'Access Denied'.  At first I thought my credentials were bad, and spent a lot of time tracking that.  But eventually debugged it to my bucket settings.  

I suggest you maybe want to add a note in the README for this error case.  **To instruct folks to ensure that 'Block all public access' is disabled.**

For what it's worth, here is my error in full:

```
python manage.py collectstatic
INFO Found credentials in shared credentials file: ~/.aws/credentials

You have requested to collect static files at the destination
location as specified in your settings.

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "/var/task/ve-test/lib/python3.7/site-packages/django_s3_storage/storage.py", line 42, in _do_wrap_errors
    return func(self, name, *args, **kwargs)
  File "/var/task/ve-test/lib/python3.7/site-packages/django_s3_storage/storage.py", line 322, in _save
    self.s3_connection.put_object(Body=content.read(), **put_params)
  File "/var/task/ve-test/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/ve-test/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/var/task/ve-test/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/task/ve-test/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/task/ve-test/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/task/ve-test/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/task/ve-test/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
    collected = self.collect()
  File "/var/task/ve-test/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
    handler(path, prefixed_path, storage)
  File "/var/task/ve-test/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 352, in copy_file
    self.storage.save(prefixed_path, source_file)
  File "/var/task/ve-test/lib/python3.7/site-packages/django/core/files/storage.py", line 52, in save
    return self._save(name, content)
  File "/var/task/ve-test/lib/python3.7/site-packages/django_s3_storage/storage.py", line 44, in _do_wrap_errors
    raise S3Error("S3Storage error at {!r}: {}".format(name, force_text(ex)))
django_s3_storage.storage.S3Error: S3Storage error at 'admin/css/widgets.css': An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

**Comment by etianen** [comment]
Thanks for the write-up. I hope that people googling your problem will find
this solution now.

I'm not sure how much info I should put in the readme about configuring the
bucket. The possible combinations of IAM permissions, bucket settings,
access certificates etc is so huge that there's massive scope for things
going wrong. There's a risk I just end up duplicating the AWS S3
documentation in the readme!

**Comment by edgarroman** [comment]
My only point was that Access Denied often leads developers to think that credentials are invalid.  If people see this issue here w/ google then I hope it helps them.

**Comment by endersonmenezes** [comment]
Thx!
